arm:
  # Publicar todos los estados de las articulaciones
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Controladores de Posición
  #base_link_motor_position_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: base_link_motor
  #  pid: {p: 0.0, i: 0.0, d: 0.0}

  motor_end_effector_position_controller:
    type: effort_controllers/JointPositionController
    joint: motor_end_effector
    pid: {p: 1.2, i: 0.0, d: 0.0}
